### ISSUE TITLE
Contribution guide should include dependencies

### ISSUE THREAD

**Issue by m8ram** [C-RH-C/crhc-cli#191]
Hi,

Installing the Python requirements on my new system failed due to some missing dependencies.

I have been able to determine the following:
- gcc
- python3-devel
- libffi-devel

So far I have not been able to determine what I need to resolve:
```
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Iast27/Include -I/home/user/.virtualenv/crhc-cli/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
      In file included from ast27/Custom/typed_ast.c:3:
      ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
          5 | #include "code.h"
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
```

For what it's worth: Version 1.5.5 of typed-ast can be installed without problem.

**Comment by waldirio** [comment]
Hello @m8ram 

Thank you for the heads up. Could you please share the baseOS that you are using? also, the version? For example, rhel8.4 or CentOS 8.1? Something like that.

With that, I'll create a fresh install, minimal installation, will collect all the requirements and will update our page.

You can use the code below
```
# dnf provides */code.h
```

This will tell you which package contains the file in question
```
# dnf provides */code.h
Updating Subscription Management repositories.
Last metadata expiration check: 1:34:09 ago on Tue 17 Oct 2023 05:48:46 PM UTC.
platform-python-debug-3.6.8-1.el8.i686 : Debug version of the Python runtime
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/include/python3.6dm/code.h

platform-python-debug-3.6.8-1.el8.x86_64 : Debug version of the Python runtime
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/include/python3.6dm/code.h
...
python39-devel-3.9.16-1.module+el8.8.0+17625+b531f198.x86_64 : Libraries and header files needed for Python development
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/include/python3.9/code.h
Filename    : /usr/include/python3.9/cpython/code.h

python39-devel-3.9.16-1.module+el8.8.0+18968+3d7b19f0.1.x86_64 : Libraries and header files needed for Python development
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/include/python3.9/code.h
Filename    : /usr/include/python3.9/cpython/code.
```

I suspect that this is `python39-devel`, but once you share the information above, I'll be able to tell you for sure which one should be around.

Thank you again for the heads up!
Waldirio

**Comment by m8ram** [comment]
Hi Waldirio,
This is on my fedora 38 (CSB) system. Since the `gcc` command line included ` -I/usr/include/python3.11` I checked python3-devel and I have `python3-devel-3.11.6-1.fc38.x86_64` installed.
Regards
Bram

**Comment by waldirio** [comment]
Hello,

Thank you! I can see the error, I believe typed-ast got deprecated and it's causing the issue, once it was supported up to python3.7. It still working on my dev env once I have multiple versions as well.

Allow me some time to review and fix it.

Thank you!
Waldirio

**Comment by waldirio** [comment]
Hello,

Please, proceed as below

Install the packages below
```
git
gcc
python3-devel
libffi-devel
```
and remove the line below from `requirements.txt`
```
typed-ast==1.4.3
```

After that, proceed with the installation, in your virtual environment
```
(crhc-cli) [root@server crhc-cli]# pip install -r requirements.txt 
```

The installation should finish with no issues.

Please, let me know if it works for you. I'll do a double check on the dependencies for this package, run all the tests and if not necessary anymore, I'll remove it.

Thank you again!
Waldirio

**Comment by m8ram** [comment]
Hi Waldirio,

Confirmed, I have deleted the virtual environment, removed the typed-ast from the requirements.tst and with the listed dependencies the installation of the python requirements now completes without errors.

The python command works but running `pyinstaller` to generate the binary does throw a traceback:
```
$ pyinstaller crhc.py 
Traceback (most recent call last):
  File "/home/bmertens/.virtualenv/crhc-cli/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/__main__.py", line 107, in run
    parser = generate_parser()
             ^^^^^^^^^^^^^^^^^
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/__main__.py", line 78, in generate_parser
    import PyInstaller.building.build_main
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/building/build_main.py", line 35, in <module>
    from PyInstaller.depend import bindepend
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/bindepend.py", line 26, in <module>
    from PyInstaller.depend import dylib, utils
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/utils.py", line 33, in <module>
    from PyInstaller.depend import bytecode
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/bytecode.py", line 95, in <module>
    _call_function_bytecode = bytecode_regex(rb"""
                              ^^^^^^^^^^^^^^^^^^^^
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/bytecode.py", line 60, in bytecode_regex
    pattern = re.sub(
              ^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/bytecode.py", line 62, in <lambda>
    lambda m: _instruction_to_regex(m[1].decode()),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bmertens/.virtualenv/crhc-cli/lib64/python3.11/site-packages/PyInstaller/depend/bytecode.py", line 40, in _instruction_to_regex
    return re.escape(bytes([dis.opmap[x]]))
                            ~~~~~~~~~^^^
KeyError: 'CALL_FUNCTION'
```

After upgrading pyinstaller to 6.1.0 and pyinstaller-hooks-contrib to 2023.10 using `pip install -U pyinstaller` the issue is resolved.

**Comment by waldirio** [comment]
Hello @m8ram 

The requirements.txt was updated to the latest version of python modules available. I tested and it's working properly.

Thank you!
Waldirio
