### ISSUE TITLE
Check/Fix the swatch list socket_summary

### ISSUE THREAD

**Issue by waldirio** [C-RH-C/crhc-cli#204]
Check/Fix the `swatch list socket_summary`, after the change #200

**Comment by waldirio** [comment]
```
# ./crhc.py swatch socket_summary
Traceback (most recent call last):
  File "/tmp/crhc-cli/crhc.py", line 12, in <module>
    parse.main_menu()
  File "/tmp/crhc-cli/parse/parse.py", line 631, in main_menu
    swatch_sub_menu()
  File "/tmp/crhc-cli/parse/parse.py", line 234, in swatch_sub_menu
    execution.swatch_socket_summary()
  File "/tmp/crhc-cli/execution/execution.py", line 626, in swatch_socket_summary
    server["hardware_type"] == "PHYSICAL"
```

**Comment by waldirio** [comment]
```
% ./crhc.py swatch socket_summary
Public Cloud ........: 14
Virtualized RHEL ....: 3872
Physical RHEL .......: 1006
Hypervisors .........: 92
----------------------
Total # of Sockets ..: 4984
```

Fixed
