### ISSUE TITLE
When revoking the token, the app get crazy

### ISSUE THREAD

**Issue by waldirio** [C-RH-C/crhc-cli#46]
```
$ ./crhc swatch list 
Traceback (most recent call last):
  File "crhc.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "parse/parse.py", line 11, in <module>
  File "credential/token.py", line 86, in get_token
  File "credential/token.py", line 114, in refresh_token
KeyError: 'access_token'
[489935] Failed to execute script 'crhc' due to unhandled exception!
```

**Comment by waldirio** [comment]
Fixed
