### ISSUE TITLE
new issue when requesting inventory information

### ISSUE THREAD

**Issue by waldirio** [C-RH-C/crhc-cli#51]
```
$ ./crhc --version
1.4.3
[wpinheir@ironman crhc]$ ./crhc inventory list --csv
Traceback (most recent call last):
  File "crhc.py", line 12, in <module>
  File "parse/parse.py", line 375, in main_menu
  File "parse/parse.py", line 106, in inventory_sub_menu
  File "report/report.py", line 207, in csv_report_inventory
KeyError: 0
[1017479] Failed to execute script 'crhc' due to unhandled exception!
```

**Comment by waldirio** [comment]
typo fixed.
