### ISSUE TITLE
Issue when passing the token, .crhc.conf empty

### ISSUE THREAD

**Issue by waldirio** [C-RH-C/crhc-cli#57]
```
# ./crhc --version
Traceback (most recent call last):
  File "crhc.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "parse/parse.py", line 14, in <module>
  File "credential/token.py", line 65, in get_token
  File "json/__init__.py", line 299, in load
  File "json/__init__.py", line 354, in loads
  File "json/decoder.py", line 339, in decode
  File "json/decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[26291] Failed to execute script 'crhc' due to unhandled exception!
```
Also, when checking the content of `~/.crhc.conf` we can see the same still empty
```
# cat .crhc.conf 
# 
```

**Comment by waldirio** [comment]
Fixed in the 1.4.4. Now the file should be created with no issues.
